os:
  - linux

# TODO: one day when container infrastructure works better change to
# sudo: false
sudo: required

cache: apt

before_install:
    - sudo apt-add-repository -y ppa:opencog-dev/ppa
    - sudo apt-get update

install:
    - sudo apt-get install -y libboost-date-time-dev \
                              libboost-filesystem-dev \
                              libboost-program-options-dev \
                              libboost-regex-dev \
                              libboost-thread-dev \
                              libboost-system-dev \
                              libboost-math-dev \
                              libboost-mpi-dev \
                              cxxtest cmake build-essential

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make -j$(nproc)
    - make tests
    - make test
